name: DailyReport

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "22 09 * * *"
    # 7:22开始执行
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: 'Set up Python'
        uses: actions/setup-python@v3
        with:
           python-version: '3.10'
           cache: 'pip'
      - name: Cache browsers
        id: cache-browsers
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\AppData\Local\ms-playwright
          key: ${{ runner.os }}-${{ hashFiles('requirements.txt') }}
      - name: 'Install requirements'
        run: |
          pip install -r requirements.txt
          playwright install --with-deps firefox
      - name: 'Working'
        run:
          python main.py ${{ secrets.username }} ${{ secrets.password }}
      - name: 'Check previous status'
        if: ${{ failure() }}
        run:
          python main.py ${{ secrets.username }} ${{ secrets.password }}
